import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import yaml from "js-yaml";

type Badge = {
  label: string;
  image: string;
  link?: string;
  alt: string;
};

type SharedCopy = {
  heroTitle: string;
  heroTagline: string;
  introLead: string;
  introTail: string;
  wiktionaryUrl: string;
  pitaQuery: string;
  githubOwner: string;
  githubRepo: string;
  npmPackage: string;
  nodeVersion: string;
  badges: Badge[];
};

const root = resolve(__dirname, "..");
const sharedPath = resolve(root, "shared-copy.yaml");
const readmePath = resolve(root, "README.md");
const webappGeneratedPath = resolve(root, "webapp/src/shared-copy.generated.ts");

function escapeTsString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`");
}

/** Replace `{github}`, `{npm}`, `{node}` placeholders in badge URLs. */
function interpolateBadgeUrl(url: string, copy: SharedCopy): string {
  return url
    .replace(/\{github\}/g, `${copy.githubOwner}/${copy.githubRepo}`)
    .replace(/\{npm\}/g, copy.npmPackage)
    .replace(/\{node\}/g, copy.nodeVersion);
}

function resolveBadges(copy: SharedCopy): Badge[] {
  return (copy.badges ?? []).map((b) => ({
    ...b,
    image: interpolateBadgeUrl(b.image, copy),
    link: b.link ? interpolateBadgeUrl(b.link, copy) : undefined,
  }));
}

function badgesToMarkdown(badges: Badge[]): string {
  return badges
    .map((b) => {
      const img = `![${b.alt}](${b.image})`;
      return b.link ? `[${img}](${b.link})` : img;
    })
    .join("\n");
}

function syncWebappGenerated(copy: SharedCopy) {
  const badges = resolveBadges(copy);
  const badgesTs = badges
    .map(
      (b) =>
        `  { label: ${JSON.stringify(b.label)}, image: ${JSON.stringify(b.image)}, ${b.link ? `link: ${JSON.stringify(b.link)}, ` : ""}alt: ${JSON.stringify(b.alt)} }`,
    )
    .join(",\n");

  const contents = `/* AUTO-GENERATED by tools/sync-shared-copy.ts. Do not edit manually. */
export const SHARED_COPY = {
  heroTitle: \`${escapeTsString(copy.heroTitle)}\`,
  heroTagline: \`${escapeTsString(copy.heroTagline)}\`,
  introLead: \`${escapeTsString(copy.introLead)}\`,
  introTail: \`${escapeTsString(copy.introTail)}\`,
  wiktionaryUrl: \`${escapeTsString(copy.wiktionaryUrl)}\`,
  pitaQuery: \`${escapeTsString(copy.pitaQuery)}\`,
  badges: [
${badgesTs},
  ] as const,
} as const;
`;
  writeFileSync(webappGeneratedPath, contents, "utf8");
}

function syncReadme(copy: SharedCopy) {
  const readme = readFileSync(readmePath, "utf8");
  const pitaUrl = `https://rhythmus.github.io/wiktionary-sdk/?q=${encodeURIComponent(copy.pitaQuery)}`;
  const introLeadSansSubject = copy.introLead.replace(/^Wiktionary\s+/u, "").trim();
  const readmeIntro = `[Wiktionary](${copy.wiktionaryUrl}) ${introLeadSansSubject} [p.i.t.a](${pitaUrl}). ${copy.introTail}`;

  const badges = resolveBadges(copy);
  const badgeMd = badgesToMarkdown(badges);

  const lines = readme.split("\n");
  if (lines.length < 8 || !lines[0].startsWith("# ")) {
    throw new Error("README hero block not in expected format.");
  }

  lines[0] = `# ${copy.heroTitle.split(" — ")[0]}`;
  lines[2] = `> ${copy.heroTagline}`;

  // Badge block: lines[4] is the demo link (=> Online demo …).
  // Insert / replace badge block between demo link and intro paragraph.
  // Convention: line 5 is blank, line 6 is badges, line 7 is blank, line 8 is intro.
  // We look for the intro line and replace everything between the demo link and it.
  const demoLineIdx = lines.findIndex((l) => l.startsWith("=> Online demo"));
  const introLineIdx = lines.findIndex((l) =>
    l.startsWith("[Wiktionary]("),
  );

  if (demoLineIdx === -1 || introLineIdx === -1) {
    throw new Error(
      "README hero block structure changed — cannot locate demo link or intro paragraph.",
    );
  }

  const before = lines.slice(0, demoLineIdx + 1);
  const after = lines.slice(introLineIdx);

  after[0] = readmeIntro;

  const rebuilt = [...before, "", badgeMd, "", ...after];
  writeFileSync(readmePath, `${rebuilt.join("\n").replace(/\n+$/u, "")}\n`, "utf8");
}

function main() {
  const raw = readFileSync(sharedPath, "utf8");
  const copy = yaml.load(raw) as SharedCopy;
  if (!copy || typeof copy !== "object") {
    throw new Error("Invalid shared-copy.yaml content.");
  }
  syncWebappGenerated(copy);
  syncReadme(copy);
  // eslint-disable-next-line no-console
  console.log("Synced shared copy to README and webapp.");
}

main();
