import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import yaml from "js-yaml";

type SharedCopy = {
  heroTitle: string;
  heroTagline: string;
  introLead: string;
  introTail: string;
  wiktionaryUrl: string;
  pitaQuery: string;
};

const root = resolve(__dirname, "..");
const sharedPath = resolve(root, "shared-copy.yaml");
const readmePath = resolve(root, "README.md");
const webappGeneratedPath = resolve(root, "webapp/src/shared-copy.generated.ts");

function escapeTsString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`");
}

function syncWebappGenerated(copy: SharedCopy) {
  const contents = `/* AUTO-GENERATED by tools/sync-shared-copy.ts. Do not edit manually. */
export const SHARED_COPY = {
  heroTitle: \`${escapeTsString(copy.heroTitle)}\`,
  heroTagline: \`${escapeTsString(copy.heroTagline)}\`,
  introLead: \`${escapeTsString(copy.introLead)}\`,
  introTail: \`${escapeTsString(copy.introTail)}\`,
  wiktionaryUrl: \`${escapeTsString(copy.wiktionaryUrl)}\`,
  pitaQuery: \`${escapeTsString(copy.pitaQuery)}\`,
} as const;
`;
  writeFileSync(webappGeneratedPath, contents, "utf8");
}

function syncReadme(copy: SharedCopy) {
  const readme = readFileSync(readmePath, "utf8");
  const pitaUrl = `https://rhythmus.github.io/wiktionary-sdk/?q=${encodeURIComponent(copy.pitaQuery)}`;
  const introLeadSansSubject = copy.introLead.replace(/^Wiktionary\s+/u, "").trim();
  const readmeIntro = `[Wiktionary](${copy.wiktionaryUrl}) ${introLeadSansSubject} [p.i.t.a](${pitaUrl}). ${copy.introTail}`;

  const lines = readme.split("\n");
  if (lines.length < 8 || !lines[0].startsWith("# ")) {
    throw new Error("README hero block not in expected format.");
  }

  lines[0] = `# ${copy.heroTitle.split(" — ")[0]}`;
  lines[2] = `> ${copy.heroTagline}`;
  lines[6] = readmeIntro;

  writeFileSync(readmePath, `${lines.join("\n").replace(/\n+$/u, "")}\n`, "utf8");
}

function main() {
  const raw = readFileSync(sharedPath, "utf8");
  const copy = yaml.load(raw) as SharedCopy;
  if (!copy || typeof copy !== "object") {
    throw new Error("Invalid shared-copy.yaml content.");
  }
  syncWebappGenerated(copy);
  syncReadme(copy);
  // eslint-disable-next-line no-console
  console.log("Synced shared copy to README and webapp.");
}

main();
