import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import yaml from "js-yaml";

type Badge = {
  label?: string;
  platform?: string;
  image: string;
  link?: string;
  alt: string;
};

type SharedCopy = {
  heroTitle: string;
  heroTagline: string;
  introLead: string;
  introTail: string;
  wiktionaryUrl: string;
  pitaQuery: string;
  githubOwner: string;
  githubRepo: string;
  npmPackage: string;
  nodeVersion: string;
  shareText: string;
  shareHashtags: string;
  heroBadges: Badge[];
  secondaryBadges: Badge[];
  shareBadges: Badge[];
};

const root = resolve(__dirname, "..");
const sharedPath = resolve(root, "shared-copy.yaml");
const readmePath = resolve(root, "README.md");
const webappGeneratedPath = resolve(root, "webapp/src/shared-copy.generated.ts");

function escapeTsString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`");
}

/** Replace all placeholders in badge URLs. */
function interpolateUrl(url: string, copy: SharedCopy): string {
  const githubSlug = `${copy.githubOwner}/${copy.githubRepo}`;
  const githubUrl = `https://github.com/${githubSlug}`;
  const shareTextEncoded = encodeURIComponent(copy.shareText ?? "");
  return url
    .replace(/\{github\}/g, githubSlug)
    .replace(/\{githubUrl\}/g, githubUrl)
    .replace(/\{npm\}/g, copy.npmPackage)
    .replace(/\{node\}/g, copy.nodeVersion)
    .replace(/\{shareTextEncoded\}/g, shareTextEncoded)
    .replace(/\{shareHashtags\}/g, copy.shareHashtags ?? "");
}

function resolveBadges(raw: Badge[] | undefined, copy: SharedCopy): Badge[] {
  return (raw ?? []).map((b) => ({
    ...b,
    image: interpolateUrl(b.image, copy),
    link: b.link ? interpolateUrl(b.link, copy) : undefined,
  }));
}

function badgesToMarkdown(badges: Badge[]): string {
  return badges
    .map((b) => {
      const img = `![${b.alt}](${b.image})`;
      return b.link ? `[${img}](${b.link})` : img;
    })
    .join("\n");
}

function badgesToInlineMarkdown(badges: Badge[]): string {
  return badges
    .map((b) => {
      const img = `![${b.alt}](${b.image})`;
      return b.link ? `[${img}](${b.link})` : img;
    })
    .join(" ");
}

function badgeToTs(b: Badge): string {
  const label = b.label ?? b.platform ?? "";
  const parts = [
    `label: ${JSON.stringify(label)}`,
    `image: ${JSON.stringify(b.image)}`,
  ];
  if (b.link) parts.push(`link: ${JSON.stringify(b.link)}`);
  parts.push(`alt: ${JSON.stringify(b.alt)}`);
  return `  { ${parts.join(", ")} }`;
}

function syncWebappGenerated(copy: SharedCopy) {
  const hero = resolveBadges(copy.heroBadges, copy);
  const secondary = resolveBadges(copy.secondaryBadges, copy);
  const shares = resolveBadges(copy.shareBadges, copy);
  const heroTs = hero.map(badgeToTs).join(",\n");
  const secondaryTs = secondary.map(badgeToTs).join(",\n");
  const sharesTs = shares.map(badgeToTs).join(",\n");

  const contents = `/* AUTO-GENERATED by tools/sync-shared-copy.ts. Do not edit manually. */
export const SHARED_COPY = {
  heroTitle: \`${escapeTsString(copy.heroTitle)}\`,
  heroTagline: \`${escapeTsString(copy.heroTagline)}\`,
  introLead: \`${escapeTsString(copy.introLead)}\`,
  introTail: \`${escapeTsString(copy.introTail)}\`,
  wiktionaryUrl: \`${escapeTsString(copy.wiktionaryUrl)}\`,
  pitaQuery: \`${escapeTsString(copy.pitaQuery)}\`,
  heroBadges: [
${heroTs},
  ] as const,
  secondaryBadges: [
${secondaryTs},
  ] as const,
  shareBadges: [
${sharesTs},
  ] as const,
} as const;
`;
  writeFileSync(webappGeneratedPath, contents, "utf8");
}

const FOOTER_MARKER = "<!-- badges:secondary -->";

function syncReadme(copy: SharedCopy) {
  const readme = readFileSync(readmePath, "utf8");
  const pitaUrl = `https://rhythmus.github.io/wiktionary-sdk/?q=${encodeURIComponent(copy.pitaQuery)}`;
  const introLeadSansSubject = copy.introLead.replace(/^Wiktionary\s+/u, "").trim();
  const readmeIntro = `[Wiktionary](${copy.wiktionaryUrl}) ${introLeadSansSubject} [p.i.t.a](${pitaUrl}). ${copy.introTail}`;

  const hero = resolveBadges(copy.heroBadges, copy);
  const secondary = resolveBadges(copy.secondaryBadges, copy);
  const shares = resolveBadges(copy.shareBadges, copy);

  const heroMd = badgesToMarkdown(hero);
  const secondaryMd = badgesToMarkdown(secondary);
  const shareMd = badgesToInlineMarkdown(shares);

  const lines = readme.split("\n");
  if (lines.length < 8 || !lines[0].startsWith("# ")) {
    throw new Error("README hero block not in expected format.");
  }

  lines[0] = `# ${copy.heroTitle.split(" — ")[0]}`;
  lines[2] = `> ${copy.heroTagline}`;

  // ── Hero badge block (between demo link and intro paragraph) ──
  const demoLineIdx = lines.findIndex((l) => l.startsWith("=> Online demo"));
  const introLineIdx = lines.findIndex((l) => l.startsWith("[Wiktionary]("));

  if (demoLineIdx === -1 || introLineIdx === -1) {
    throw new Error(
      "README hero block structure changed — cannot locate demo link or intro paragraph.",
    );
  }

  const before = lines.slice(0, demoLineIdx + 1);
  const after = lines.slice(introLineIdx);
  after[0] = readmeIntro;

  const rebuilt = [...before, "", heroMd, "", ...after];

  // ── Footer badge block (secondary + share, anchored by marker) ──
  const footerBlock = [
    FOOTER_MARKER,
    "",
    secondaryMd,
    "",
    shareMd,
  ].join("\n");

  const markerIdx = rebuilt.findIndex((l) => l.trim() === FOOTER_MARKER);
  if (markerIdx !== -1) {
    // Find extent of existing footer block: everything from marker to next
    // blank-line-then-content or EOF.
    let endIdx = markerIdx + 1;
    while (endIdx < rebuilt.length) {
      // Stop when we hit a line that is clearly non-badge content (heading, paragraph, etc.)
      // after the share row. A simple heuristic: a non-empty line that doesn't start with
      // `[` or `!` (badge markdown) and isn't blank.
      const l = rebuilt[endIdx].trim();
      if (l === "") {
        endIdx++;
        continue;
      }
      if (l.startsWith("[![") || l.startsWith("![")) {
        endIdx++;
        continue;
      }
      break;
    }
    rebuilt.splice(markerIdx, endIdx - markerIdx, ...footerBlock.split("\n"));
  } else {
    // First run: insert before the very last line (which is empty or EOF)
    rebuilt.push("", ...footerBlock.split("\n"));
  }

  writeFileSync(readmePath, `${rebuilt.join("\n").replace(/\n+$/u, "")}\n`, "utf8");
}

function main() {
  const raw = readFileSync(sharedPath, "utf8");
  const copy = yaml.load(raw) as SharedCopy;
  if (!copy || typeof copy !== "object") {
    throw new Error("Invalid shared-copy.yaml content.");
  }
  syncWebappGenerated(copy);
  syncReadme(copy);
  // eslint-disable-next-line no-console
  console.log("Synced shared copy to README and webapp.");
}

main();
